### ISSUE TITLE
Error does not always have a cause in catch block. Leading to another exception.

### ISSUE THREAD

**Issue by whostolebenfrog** [logzio/logzio-nodejs#48]
I'm running the latest version of the library and periodically get errors like this:

```
3|neo4j-ap | TypeError: Cannot read property 'code' of undefined
3|neo4j-ap |     at request.post.then.catch (/usr/src/app/node_modules/logzio-nodejs/lib/logzio-nodejs.js:287:45)
3|neo4j-ap |     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
3|neo4j-ap |     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
3|neo4j-ap |     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
3|neo4j-ap |     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
3|neo4j-ap |     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:690:18)
3|neo4j-ap |     at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
3|neo4j-ap |     at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:131:9)
3|neo4j-ap |     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:147:5)
3|neo4j-ap |     at Immediate.Async.drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
3|neo4j-ap |     at Immediate.args.(anonymous function) (/usr/src/app/node_modules/event-loop-inspector/index.js:138:29)
3|neo4j-ap |     at runCallback (timers.js:810:20)
3|neo4j-ap |     at tryOnImmediate (timers.js:768:5)
3|neo4j-ap |     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

It seems that it's not safe to assume the err var has a cause or code.

**Comment by idohalevi** [comment]
@whostolebenfrog
Thank you for letting us know. I will try to publish #49 ASAP
